export const ENV_VARS = {
  GOOGLE__OAUTH_CLIENT_ID: 'GOOGLE_OAUTH_CLIENT_ID',
  GOOGLE__OAUTH_CLIENT_SECRET: 'GOOGLE_OAUTH_CLIENT_SECRET',
  GOOGLE__OAUTH_REDIRECT_URI: 'GOOGLE_OAUTH_REDIRECT_URI',
  GOOGLE__OAUTH_PROJECT_ID: 'GOOGLE_OAUTH_PROJECT_ID',
};
